### ISSUE TITLE
Add support for Nano Pi R5S

### ISSUE THREAD

**Issue by nicklasfrahm** [siderolabs/sbc-rockchip#12]
Hi,

I would love to give Talos a spin on my Nano Pi R5S which is based on the RK3568. Do you have any material or documentation on your build system? I would love to contribute and create an overlay.

**Comment by frezbo** [comment]
Running `make help` should provide the steps to setup a buildx builder.

**Comment by frezbo** [comment]
Also https://www.talos.dev/v1.7/advanced/overlays/
