### ISSUE TITLE
feature request: add support for `rk3328-orangepi-r1-plus-lts`

### ISSUE THREAD

**Issue by giautm** [siderolabs/sbc-rockchip#8]
u-boot link: https://github.com/u-boot/u-boot/blob/9468bf3a69b05bda05adb06f954b089ace301afc/configs/orangepi-r1-plus-lts-rk3328_defconfig#L12C29-L12C56

I wanna to build the image for this board (I've one). But not family with the workflow yet. Please guidance me.

I saw a opening PR for support. I can follow it to add support for `rk3328-orangepi-r1-plus-lts`. But unknown how to build and testing it locally.

**Comment by giautm** [comment]
I able to use the Rock64 image and it booting fine on `rk3328-orangepi-r1-plus-lts`. However, it can't recognizes WAN/LAN ports correctly and in a crash-loop.

**Comment by frezbo** [comment]
> u-boot link: https://github.com/u-boot/u-boot/blob/9468bf3a69b05bda05adb06f954b089ace301afc/configs/orangepi-r1-plus-lts-rk3328_defconfig#L12C29-L12C56
> 
> I wanna to build the image for this board (I've one). But not family with the workflow yet. Please guidance me.
> 
> I saw a opening PR for support. I can follow it to add support for `rk3328-orangepi-r1-plus-lts`. But unknown how to build and testing it locally.

you can check the docs here: https://www.talos.dev/v1.7/advanced/overlays/

**Comment by giautm** [comment]
The PR is ready for review: https://github.com/siderolabs/sbc-rockchip/pull/9

**Comment by giautm** [comment]
Thank you for review

**Comment by giautm** [comment]
```shell
root@ubuntu:~# docker run --rm -t \
  -v $PWD/_out:/out \
  -v /dev:/dev --privileged \
  ghcr.io/siderolabs/imager:v1.7.0-alpha.1-23-g0361ff895 orangepi-r1-plus-lts \
  --arch arm64 \
  --overlay-image=ghcr.io/siderolabs/sbc-rockchip:v0.1.0-alpha.2-3-g50e082e \
  --overlay-name=orangepi-r1-plus-lts
profile ready:
arch: arm64
platform: metal
secureboot: false
version: v1.7.0-alpha.1-23-g0361ff895
input:
  kernel:
    path: /usr/install/arm64/vmlinuz
  initramfs:
    path: /usr/install/arm64/initramfs.xz
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.7.0-alpha.1-23-g0361ff895
overlay:
  name: orangepi-r1-plus-lts
  image:
    imageRef: ghcr.io/siderolabs/sbc-rockchip:v0.1.0-alpha.2-3-g50e082e
output:
  kind: image
  imageOptions:
    diskSize: 1306525696
    diskFormat: raw
  outFormat: .xz
skipped initramfs rebuild (no system extensions)
kernel command line: talos.platform=metal console=tty0 console=ttyS2,1500000n8 sysctl.kernel.kexec_load_disabled=1 talos.dashboard.disabled=1 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512
disk image ready
output asset path: /out/metal-arm64.raw
compression done: /out/metal-arm64.raw.xz
```
